---
- title: Développement web
  content: Votre application grand public ou à usage interne, développée sur-mesure.
  icon: "/icons/development.svg"
- title: 'Site vitrine '
  content: Présentez votre entreprise et vos produits au grand public
  icon: "/icons/web.svg"
- title: 'E-commerce '
  content: Vendez vos produits en service via une interface intuitive, fiable et sûre
  icon: "/icons/ecommerce.svg"
- title: 'Autres ? '
  content: Vous avez une idée de développement de projet ? Contactez-nous
  icon: "/icons/idea.svg"
