name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: telescoop.fr
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 42722
          script: |
            FRONTEND_PATH="/telescoop/telescoop-site-vitrine/frontend"
            STATIC_PATH="/telescoop/telescoop-site-vitrine/static"

            sudo bash -c "
              git config --global --add safe.directory $FRONTEND_PATH
              cd $FRONTEND_PATH
              source /root/.nvm/nvm.sh
              node_version=\$(cat .nvmrc)
              git fetch origin main
              git reset --hard origin/main
              rm -rf .astro dist node_modules/.astro
              nvm exec \$node_version npm install
              nvm exec \$node_version npm run build
              rm -rf $STATIC_PATH/*
              cp -r dist/* $STATIC_PATH/
              chown -R www-data:www-data $STATIC_PATH
            "
